import { ProbabilityEChart, ScorelineHeatmap } from '@/components/Charts';
import { ConfidenceChip, DataStatePanel, MatchCard, TruthChip, WarningBanner } from '@/components/Cards';
import { loadAllPredictions, loadOverview } from '@/lib/data';
import { isPredictorDisabled, packAgeLabel } from '@/lib/status';

export default function Page() {
  const overview = loadOverview();
  const p = loadAllPredictions()[0];
  const disabled = isPredictorDisabled(overview.generated_at);
  return <div className="space-y-6">
    <header className="page-header"><h1 className="text-3xl font-semibold">Match Predictor</h1><p className="mt-2 text-sm text-[#A8B4C8]">Static lookup. No odds. Not betting advice.</p></header>
    <DataStatePanel generatedAt={overview.generated_at} />
    <section className="card" aria-labelledby="selector-title"><h2 id="selector-title" className="mb-3 font-semibold">Forecast selector</h2><div className="selector-grid"><select aria-label="Competition" className="select-control"><option>{p?.competition_id}</option></select><select aria-label="Season" className="select-control"><option>{p?.season_id}</option></select><select aria-label="Home team" className="select-control"><option>{p?.home_team ?? p?.home_team_id}</option></select><select aria-label="Away team" className="select-control"><option>{p?.away_team ?? p?.away_team_id}</option></select><button className="select-control disabled:opacity-50" disabled={disabled} aria-describedby="predictor-state">Run static lookup</button></div><p id="predictor-state" className="mt-3 text-xs text-[#A8B4C8]">Pack: {packAgeLabel(overview.generated_at)} · {disabled ? 'Disabled >72h; showing last-known data.' : 'Ready.'}</p></section>
    {p ? <><section className="headline-grid"><MatchCard p={p} /><aside className="card" aria-label="Prediction truth confidence freshness and model version"><h2 className="font-semibold">Confidence & source state</h2><div className="predictor-meta-grid mt-4"><div><div className="text-xs text-[#A8B4C8]">Truth</div><TruthChip value={p.data_truth_mode} /></div><div><div className="text-xs text-[#A8B4C8]">Confidence</div><ConfidenceChip value={p.confidence_label} /></div><div><div className="text-xs text-[#A8B4C8]">Freshness</div><p className="font-mono text-sm">{Object.entries(p.source_freshness_summary ?? { sample_football_fixtures: 'FRESH' }).map(([k, v]) => `${k} ${v}`).join(', ')}</p></div><div><div className="text-xs text-[#A8B4C8]">Model</div><p className="font-mono text-sm">{p.model_version}</p></div></div></aside></section><section className="chart-grid"><div className="card chart-card"><h2 className="font-semibold">Win / Draw / Away probability</h2><ProbabilityEChart prediction={p} /></div><div className="card chart-card"><h2 className="font-semibold">Scoreline heatmap</h2><ScorelineHeatmap prediction={p} /></div></section><section className="chart-grid"><div className="card"><h2 className="font-semibold">Top drivers</h2><ul className="mt-3 space-y-2 text-sm text-[#A8B4C8]">{p.top_drivers.slice(0, 5).map(d => <li key={d.name}><span className={d.impact >= 0 ? 'text-[#14B8A6]' : 'text-[#F472B6]'}>{d.impact >= 0 ? '+' : ''}{d.impact.toFixed(2)}</span> · {d.name.replaceAll('_', ' ')}</li>)}</ul><p className="mt-4 text-xs text-[#A8B4C8]">Driver impact is descriptive and does not imply causality.</p></div><div className="card"><h2 className="font-semibold">Expected goals & extras</h2><div className="source-chip-row mt-3 text-sm"><span className="chip">xG home {p.expected_goals_home.toFixed(2)}</span><span className="chip">xG away {p.expected_goals_away.toFixed(2)}</span><span className="chip">Market odds not used</span><span className="chip truth-warn">SAMPLE baseline</span></div></div></section><WarningBanner tone="warn">Caveat: SAMPLE_ONLY baseline data. Market odds not used in this prediction. Lineups are not used. Treat as LOW confidence and not as betting advice.</WarningBanner></> : <WarningBanner tone="err">Forecast pack parse failed. Showing no match because no last-known fixture is available in this static build.</WarningBanner>}
  </div>;
}
