import { ProbabilityEChart, ScorelineHeatmap } from '@/components/Charts';
import { ConfidenceChip, DataStatePanel, MatchCard, TruthChip, WarningBanner } from '@/components/Cards';
import { loadAllPredictions, loadOverview } from '@/lib/data';
import { getDictionary, type Locale } from '@/lib/i18n';
import { isPredictorDisabled, packAgeLabel } from '@/lib/status';

export function MatchPredictorPage({ locale = 'zh' }: { locale?: Locale }) {
  const t = getDictionary(locale);
  const overview = loadOverview();
  const p = loadAllPredictions()[0];
  const disabled = isPredictorDisabled(overview.generated_at);
  return <div className="space-y-6">
    <header className="page-header"><h1 className="text-3xl font-semibold">{t.match.title}</h1><p className="mt-2 text-sm text-[#A8B4C8]">{t.match.subtitle}</p></header>
    <DataStatePanel generatedAt={overview.generated_at} t={t} />
    <section className="card" aria-labelledby="selector-title"><h2 id="selector-title" className="mb-3 font-semibold">{t.match.selector}</h2><div className="selector-grid"><select aria-label={t.match.competition} className="select-control"><option>{p?.competition_id}</option></select><select aria-label={t.match.season} className="select-control"><option>{p?.season_id}</option></select><select aria-label={t.match.homeTeam} className="select-control"><option>{p?.home_team ?? p?.home_team_id}</option></select><select aria-label={t.match.awayTeam} className="select-control"><option>{p?.away_team ?? p?.away_team_id}</option></select><button className="select-control disabled:opacity-50" disabled={disabled} aria-describedby="predictor-state">{t.match.run}</button></div><p id="predictor-state" className="mt-3 text-xs text-[#A8B4C8]">{t.common.pack}: {packAgeLabel(overview.generated_at)} · {disabled ? t.match.disabledState : t.match.readyState}</p></section>
    {p ? <><section className="headline-grid"><MatchCard p={p} t={t} /><aside className="card" aria-label="Prediction truth confidence freshness and model version"><h2 className="font-semibold">{t.match.sourceState}</h2><div className="predictor-meta-grid mt-4"><div><div className="text-xs text-[#A8B4C8]">{t.common.truth}</div><TruthChip value={p.data_truth_mode} /></div><div><div className="text-xs text-[#A8B4C8]">{t.common.confidence}</div><ConfidenceChip value={p.confidence_label} t={t} /></div><div><div className="text-xs text-[#A8B4C8]">{t.common.freshness}</div><p className="font-mono text-sm">{Object.entries(p.source_freshness_summary ?? { sample_football_fixtures: 'FRESH' }).map(([k, v]) => `${k} ${v}`).join(', ')}</p></div><div><div className="text-xs text-[#A8B4C8]">{t.common.model}</div><p className="font-mono text-sm">{p.model_version}</p></div></div></aside></section><section className="chart-grid"><div className="card chart-card"><h2 className="font-semibold">{t.match.probabilityChart}</h2><ProbabilityEChart prediction={p} t={t} /></div><div className="card chart-card"><h2 className="font-semibold">{t.match.heatmap}</h2><ScorelineHeatmap prediction={p} t={t} /></div></section><section className="chart-grid"><div className="card"><h2 className="font-semibold">{t.match.topDrivers}</h2><ul className="mt-3 space-y-2 text-sm text-[#A8B4C8]">{p.top_drivers.slice(0, 5).map(d => <li key={d.name}><span className={d.impact >= 0 ? 'text-[#14B8A6]' : 'text-[#F472B6]'}>{d.impact >= 0 ? '+' : ''}{d.impact.toFixed(2)}</span> · {d.name.replaceAll('_', ' ')}</li>)}</ul><p className="mt-4 text-xs text-[#A8B4C8]">{t.match.driverNote}</p></div><div className="card"><h2 className="font-semibold">{t.match.xgExtras}</h2><div className="source-chip-row mt-3 text-sm"><span className="chip">xG home {p.expected_goals_home.toFixed(2)}</span><span className="chip">xG away {p.expected_goals_away.toFixed(2)}</span><span className="chip">{t.common.marketOddsNotUsed}</span><span className="chip truth-warn">SAMPLE baseline</span></div></div></section><WarningBanner tone="warn">{t.match.caveat}</WarningBanner></> : <WarningBanner tone="err">{t.match.parseFailed}</WarningBanner>}
  </div>;
}
export default function Page() { return <MatchPredictorPage locale="zh" />; }
