import { RadarChart } from '@/components/Charts';
import { TruthChip } from '@/components/Cards';
import { loadTeamCompare } from '@/lib/data';

export default function Page() {
  const data = loadTeamCompare();
  const teams = data.teams.slice(0, 2);
  return <div className="space-y-6"><header className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-3xl font-semibold">Team Comparison</h1><p className="mt-2 text-sm text-[#A8B4C8]">Baseline normalized strengths from the static pack; no live roster or odds signals.</p></div><TruthChip value={data.data_truth_mode_summary} /></header><section className="card"><div className="grid gap-3 md:grid-cols-3"><select aria-label="Team A" className="select-control"><option>{teams[0]?.canonical_name}</option></select><select aria-label="Team B" className="select-control"><option>{teams[1]?.canonical_name}</option></select><select aria-label="Competition context" className="select-control"><option>Static sample context</option></select></div></section><section className="grid gap-4 lg:grid-cols-2"><div className="card"><h2 className="font-semibold">Strength radar</h2><RadarChart teams={teams.map(t => t.canonical_name)} /></div><div className="card"><h2 className="font-semibold">Recent form timeline</h2><div className="mt-4 grid gap-3">{teams.map((team, index) => <div key={team.team_id} className="rounded bg-[#13203A] p-3"><div className="mb-2 font-semibold">{team.canonical_name}</div><div className="flex flex-wrap gap-2" aria-label={`${team.canonical_name} recent form`}>{['W', 'D', 'L', 'W', 'W'].slice(index, index + 4).map((r, i) => <span key={`${r}-${i}`} className={`chip ${r === 'W' ? 'truth-ok' : r === 'D' ? 'truth-warn' : 'truth-err'}`}>{r}</span>)}</div></div>)}</div></div></section><section className="card"><h2 className="font-semibold">Head-to-head caveat</h2><p className="mt-2 text-sm text-[#A8B4C8]">The P2 baseline pack has limited sample H2H rows, so this page shows normalized comparison profiles and an explicit caveat instead of pretending full live history exists.</p></section></div>;
}
